@startuml
'https://plantuml.com/class-diagram

class ToDoEntry {
' a specific entry that shows up in the to-do lists

- String description
- String dueDate

+ getDescription(): String
+ setDescription(String): void
+ getDueDate(): String
+ setDueDate(String): void

}

class ToDoList {
' the to-do list

- String title
- List<ToDoEntry> entries

+ getTitle(): String
+ setTitle(String): String

+ getEntry(int): ToDoEntry
+ setEntry(int, ToDoEntry): void
+ removeEntry(int): void

+ getList(): List<ToDoEntry>

}

'class ToDoManager {
'
'   - int numToDoList
'   - List<ToDoList> list
'
'   + addToDoList(String): void
'   + removeToDoList(int): void
'   + getToDoLists(): List<ToDoList>
'
'}

class Application {

    + main(String[] args)
    + start(Stage stage)

}

ToDoList --o ToDoEntry
' ToDoManager --o ToDoList
' Application -- ToDoManager
Application -- ToDoList

@enduml